### ISSUE TITLE
Add f:format.case

### ISSUE THREAD

**Issue by febLey** [febLey/vscode-typo3-fluid-snippets#1]
https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Format/Case.html

**Comment by rowild** [comment]
This seems to be implemented (and enhanced?) already. Close issue?

**Comment by X-Tender** [comment]
Hm, it didn't look like it's implemented.

**Comment by rowild** [comment]
True - my mistake! No idea, why I came to the point to write this... sorry!
Is it possible to edit an already existing PR?
