### ISSUE TITLE
This extension disables typescript

### ISSUE THREAD

**Issue by rowild** [febLey/vscode-typo3-fluid-snippets#2]
Kind of the opposite behaviour known from phpStorm, where Typescript is configured very strongly and overwrites TypoScript, here in VS Code it seems to be the other way around. Upon installing this extension, the identification of typescript fails (see file icon, when test-creating a test.ts file).

Is there a way to configure that? I already have:

```
"files.associations": {
    "*.t3": "typoscript",
    "*.t3s": "typoscript",
    "*.setup.ts": "typoscript",
    "*.constants.ts": "typoscript",
    "*.ts": "typescript"
}
```

**Comment by febLey** [comment]
The extension shouldn't mess with your typescript files, because it only contains snippets and these will be enabled in html files.
Do you have a typoscript extension installed?

**Comment by rowild** [comment]
@febLey Sorry for the late response! – I don't know what happened last time. Currently everything seems to work fine. (It might have been that I had installed another typoscript extension...)
So I am closing this issue.
